[project]
name = "text2sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "langchain>=0.3.4",
    "langchain-openai>=0.2.3",
    "langchain-community>=0.3.3",
    "gradio>=5.1.0",
]
